xyo: # XYO Configurations

  nodes: # Config for all nodes on the network

    discovery: # Configuration for how nodes will find one another

      subnet: # Default ports for nodes wishing to be found

        ports: 
          - 15555
          - 15556
          - 15557
          - 15558
          - 15559
      
      knownNodes: # A list of Nodes known to be on common on the network
      
        - hostname: alpha.xyo-known-host.com
          port: 10001
        - hostname: beta.xyo-known-host.com
          port: 10002
        - hostname: omega.xyo-known-host.com
          port: 10003
        - hostname: theta.xyo-known-host.com
          port: 10004